name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  workflow_dispatch:
jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: create toolchains dir
      shell: bash
      run: mkdir toolchains
    - uses: ./
      with: 
        api: '33'
        arch: 'aarch64'
        install-location: 'toolchains'
        force: true
